### ISSUE TITLE
How do you train the model?

### ISSUE THREAD

**Issue by holleyliu** [cojocchen/covid19_critically_ill#1]
Hi:

Excellent job! Would you please release the training code? Much thanks.

Best regards.

**Comment by cojocchen** [comment]
Thank you for your interest. Since we do not get the permission of releasing the data, there is no plan in releasing the training code so far. You can find more details regarding the training process in our paper: https://www.nature.com/articles/s41467-020-17280-8 . If you encounter any problem in implementing training code, you can post it here.

**Comment by jefferyUstc** [comment]
> Thank you for your interest. Since we do not get the permission of releasing the data, there is no plan in releasing the training code so far. You can find more details regarding the training process in our paper: https://www.nature.com/articles/s41467-020-17280-8 . If you encounter any problem in implementing training code, you can post it here.

According to my understanding, holleyliu wants the model building and traning codes, nothing about the datasets.

**Comment by cojocchen** [comment]
I am afraid we have no plan of releasing training code at this moment.

**Comment by cojocchen** [comment]
> > Thank you for your interest. Since we do not get the permission of releasing the data, there is no plan in releasing the training code so far. You can find more details regarding the training process in our paper: https://www.nature.com/articles/s41467-020-17280-8 . If you encounter any problem in implementing training code, you can post it here.
> 
> According to my understanding, holleyliu wants the model building and traning codes, nothing about the datasets.

I am afraid we have no plan of releasing training code at this moment.

**Comment by holleyliu** [comment]
The concerns have been solved. Thanks.
