### ISSUE TITLE
how to get coax coefficient according to deep learning model

### ISSUE THREAD

**Issue by GhostQ99** [cojocchen/covid19_critically_ill#5]
Hi, Wenhua. I am really inspired by your work. But still got a little confused. In the prediction.py, you fix the coefficient , I want to know how you get them. For your earlier reply, you said that your work is based on DeepSurv, but I read the DeepSurv paper, there is also no mention about how to get the coefficient.

**Comment by AINIVERSHERRY** [comment]
金鑫已收到来信，祝工作生活愉快！

**Comment by cojocchen** [comment]
Could you please specify what are 'coax coefficient' referring to? E.g. which line of code or paper.
We did not use this term in our code or paper.

**Comment by 71-71** [comment]
Dear Chen:
Sorry for unclear expression in the last email. In your release codes, prediction.py, line 130-140, you writelike&nbsp;'('Malignancy', 1.06741622)',
I want to how to get 1.06741622 from deep learning model for example?


Thanks for your kindly reply!


yi 




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cojocchen/covid19_critically_ill"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 中午11:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cojocchen/covid19_critically_ill] how to get coax coefficient according to deep learning model (Issue #5)





 
Could you please specify what are 'coax coefficient' referring to? E.g. which line of code or paper.
 We did not use this term in our code or paper.

**Comment by 71-71** [comment]
> 
Sorry for unclear expression in the last email. In your release codes, prediction.py, line 130-140, you writelike '('Malignancy', 1.06741622)',I want to how to get 1.06741622 from deep learning model for example?
Thank you for your kindly reply!

**Comment by cojocchen** [comment]
I repost 71-71's response in email here for others reference:

> In your release codes, prediction.py, line 130-140, you write '('Malignancy', 1.06741622)',
> I want to how to get 1.06741622 from deep learning model for example?

These are not from DL model, but to process the output of DL model. It is a linear rigid regression model which corresponds to the nomogram in Fig. 3 of the paper. For how to compute the parameter, please refer to "Method-Deep learning survival Cox model" section in the paper. We take away the import of related ML lib and hard code these parameters in the program for inference efficiency purpose.

**Comment by cojocchen** [comment]
I close the ticket as there is no further questions.

**Comment by AINIVERSHERRY** [comment]
金鑫已收到来信，祝工作生活愉快！

**Comment by AINIVERSHERRY** [comment]
金鑫已收到来信，祝工作生活愉快！
